<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_61562cd08c9b3',
	'title' => __( 'General Catalog Fields', 'zettaiwp' ),
	'fields' => array(
		array(
			'key' => 'field_61562cd0a36cf',
			'label' => __( 'Year', 'zettaiwp' ),
			'name' => 'year',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_61562cd0a715f',
			'label' => __( 'MPAA film ratings', 'zettaiwp' ),
			'name' => 'mpaa_film_ratings',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'g' => __( 'G - General Audiences', 'zettaiwp' ),
				'pg' => __( 'PG - Parental Guidance Suggested', 'zettaiwp' ),
				'pg-13' => __( 'PG-13 - Parents Strongly Cautioned', 'zettaiwp' ),
				'r' => __( 'R - Restricted', 'zettaiwp' ),
				'nc-17' => __( 'NC-17 - Adults Only', 'zettaiwp' ),
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_61562cd0c0b35',
			'label' => __( 'Promo Phrase', 'zettaiwp' ),
			'name' => 'promo_phrase',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_61562cd0c45b4',
			'label' => __( 'Background Image', 'zettaiwp' ),
			'name' => 'poster_background',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'large',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_61562cd0cbaaf',
			'label' => __( 'Has Trailer', 'zettaiwp' ),
			'name' => 'has_trailer',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_61562cd0cf513',
			'label' => __( 'Trailer Image', 'zettaiwp' ),
			'name' => 'trailer_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_61562cd0cbaaf',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_61562cd0d2f94',
			'label' => __( 'Trailer', 'zettaiwp' ),
			'name' => 'trailer',
			'aria-label' => '',
			'type' => 'oembed',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_61562cd0cbaaf',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'width' => '',
			'height' => 250,
		),
		array(
			'key' => 'field_61562cd0d6a04',
			'label' => __( 'Actor & Character Select', 'zettaiwp' ),
			'name' => 'actor_&_character_select',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => __( 'Add', 'zettaiwp' ),
			'sub_fields' => array(
				array(
					'key' => 'field_61562cd117e48',
					'label' => __( 'Select Actor', 'zettaiwp' ),
					'name' => 'select_actor',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'characters_voice_actors',
					'field_type' => 'select',
					'allow_null' => 0,
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 0,
					'return_format' => 'id',
					'multiple' => 0,
					'bidirectional_target' => array(
					),
					'parent_repeater' => 'field_61562cd0d6a04',
				),
				array(
					'key' => 'field_61562cd11b8c0',
					'label' => __( 'As Character', 'zettaiwp' ),
					'name' => 'as_character',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_61562cd0d6a04',
				),
			),
			'rows_per_page' => 20,
		),
		array(
			'key' => 'field_61562cd0da46d',
			'label' => __( 'Staff Select', 'zettaiwp' ),
			'name' => 'staff_select',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => __( 'Add', 'zettaiwp' ),
			'sub_fields' => array(
				array(
					'key' => 'field_61562cd12e8f8',
					'label' => __( 'Select Staff', 'zettaiwp' ),
					'name' => 'select_staff',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'staff',
					'field_type' => 'select',
					'allow_null' => 0,
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 0,
					'return_format' => 'id',
					'multiple' => 0,
					'bidirectional_target' => array(
					),
					'parent_repeater' => 'field_61562cd0da46d',
				),
				array(
					'key' => 'field_61562cd1323f7',
					'label' => __( 'Position', 'zettaiwp' ),
					'name' => 'position',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'director' => __( 'Director', 'zettaiwp' ),
						'writer' => __( 'Writer', 'zettaiwp' ),
						'producer' => __( 'Producer', 'zettaiwp' ),
						'creator' => __( 'Creator', 'zettaiwp' ),
						'manga' => __( 'Original Manga', 'zettaiwp' ),
						'editor' => __( 'Editor', 'zettaiwp' ),
						'music' => __( 'Music Composer', 'zettaiwp' ),
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 1,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'label',
					'placeholder' => '',
					'parent_repeater' => 'field_61562cd0da46d',
				),
			),
			'rows_per_page' => 20,
		),
		array(
			'key' => 'field_61562cd0ddeb7',
			'label' => __( 'Full Story', 'zettaiwp' ),
			'name' => 'full_story',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'series',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'movies',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_61460221f2201',
	'title' => __( 'Staff Fields', 'zettaiwp' ),
	'fields' => array(
		array(
			'key' => 'field_614602551126a',
			'label' => __( 'Thumbnail', 'zettaiwp' ),
			'name' => 'thumbnail_staff',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'characters_voice_actors',
			),
		),
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'staff',
			),
		),
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'category',
			),
		),
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'genres',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5bbbde3aeb037',
	'title' => __( 'Theme Settings Fields', 'zettaiwp' ),
	'fields' => array(
		array(
			'key' => 'field_5bc4b5cc10e35',
			'label' => __( 'Navbar', 'zettaiwp' ),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_5bbbde48dc573',
			'label' => __( 'Upload logo', 'zettaiwp' ),
			'name' => 'upload_logo',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => __( 'Logo for normal mode. It can be used with PNG or SVG format.', 'zettaiwp' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5cb5e97fef5be',
			'label' => __( 'Upload responsive logo', 'zettaiwp' ),
			'name' => 'upload_responsive_logo',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5c73263bbea28',
			'label' => __( 'Navbar height', 'zettaiwp' ),
			'name' => 'navbar_height',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 70,
			'placeholder' => 70,
			'prepend' => '',
			'append' => 'px',
			'min' => 70,
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5c7311f2e5c9d',
			'label' => __( 'Logo height', 'zettaiwp' ),
			'name' => 'logo_height',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 50,
			'placeholder' => 50,
			'prepend' => '',
			'append' => 'px',
			'min' => 30,
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5c76f73b388c5',
			'label' => __( 'Logo shrink', 'zettaiwp' ),
			'name' => 'navbar_shrink',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5bd88c1c7aa15',
			'label' => __( 'Options', 'zettaiwp' ),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_5bf3387dabbad',
			'label' => __( 'Use Fade effect for load pages', 'zettaiwp' ),
			'name' => 'fade_effect',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5bf49198bfac5',
			'label' => __( 'Activate Load Bar', 'zettaiwp' ),
			'name' => 'activate_load_bar',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c842d483cc1d',
			'label' => __( 'Load Bar color', 'zettaiwp' ),
			'name' => 'load_bar_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bf49198bfac5',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#5f42e7',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5bf4939926f58',
			'label' => __( 'Fixed navbar', 'zettaiwp' ),
			'name' => 'fixed_navbar',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c76d23c4bff0',
			'label' => __( 'Border navbar', 'zettaiwp' ),
			'name' => 'border_navbar',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c76d26c4bff1',
			'label' => __( 'Border menu', 'zettaiwp' ),
			'name' => 'border_sidenav',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5d8f818b579cd',
			'label' => __( 'Border footer', 'zettaiwp' ),
			'name' => 'border_footer',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c799c1099145',
			'label' => __( 'Side menu font size', 'zettaiwp' ),
			'name' => 'side_menu_font_size',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 14,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5c7e98a2d2f97',
			'label' => __( 'Rounded corners', 'zettaiwp' ),
			'name' => 'rounded_corners',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_618a726c6dd35',
			'label' => __( 'All Movies Link', 'zettaiwp' ),
			'name' => 'all_movies_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'http://127.0.0.1/demos/zettai-free/movies',
			'placeholder' => '',
		),
		array(
			'key' => 'field_618a722c6dd34',
			'label' => __( 'All Series Link', 'zettaiwp' ),
			'name' => 'all_series_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'http://127.0.0.1/demos/zettai-free/series',
			'placeholder' => '',
		),
		array(
			'key' => 'field_618ab08b99aa9',
			'label' => __( 'All Reviews Link', 'zettaiwp' ),
			'name' => 'all_reviews_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'http://127.0.0.1/demos/zettai-free/reviews',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5da61bb2f90b7',
			'label' => __( 'Posts, Archives and Search', 'zettaiwp' ),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_5daa584489131',
			'label' => __( 'Popular reads title', 'zettaiwp' ),
			'name' => 'popular_reads_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Popular reads',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5daa5eedc63ee',
			'label' => __( 'Popular reads title color', 'zettaiwp' ),
			'name' => 'popular_reads_title_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#212529',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5daa5f16c63ef',
			'label' => __( 'Popular reads post quantity', 'zettaiwp' ),
			'name' => 'popular_reads_post_qty',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 5,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'Posts',
			'min' => 1,
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5da725aef5d61',
			'label' => __( 'Display time', 'zettaiwp' ),
			'name' => 'display_time',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5daa5f7fc63f0',
			'label' => __( 'Display categories', 'zettaiwp' ),
			'name' => 'display_cats',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5da6159744b25',
			'label' => __( 'Display tags', 'zettaiwp' ),
			'name' => 'display_tags',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5da61bebf90b8',
			'label' => __( 'Display excerpt', 'zettaiwp' ),
			'name' => 'display_excerpt',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5daa5f99c63f1',
			'label' => __( 'Display authors', 'zettaiwp' ),
			'name' => 'display_authors',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5ec55ca23dc8d',
			'label' => __( 'Capital Letter (Drop Cap)', 'zettaiwp' ),
			'name' => 'capital_letter',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c07f66d0eb48',
			'label' => __( 'Styling', 'zettaiwp' ),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_5c3b80bd63a90',
			'label' => __( 'Text color', 'zettaiwp' ),
			'name' => 'text_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#212529',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5c0979bd28581',
			'label' => __( 'Link color', 'zettaiwp' ),
			'name' => 'link_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#212529',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5c07eac0aecd4',
			'label' => __( 'Hover color', 'zettaiwp' ),
			'name' => 'hover_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#909090',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5c4f579e064e4',
			'label' => __( 'Navbar background', 'zettaiwp' ),
			'name' => 'navbar_background',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#f8f9fa',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5c798747af6ce',
			'label' => __( 'Hamburger menu color', 'zettaiwp' ),
			'name' => 'hamburger_menu_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#212529',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5d8f7fc6c1d24',
			'label' => __( 'Sidenav background', 'zettaiwp' ),
			'name' => 'sidenav_background',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FFFFFF',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5ce30afd0fcd9',
			'label' => __( 'Sidenav menu text color', 'zettaiwp' ),
			'name' => 'sidenav_text_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#333333',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5dab9f8aa60ee',
			'label' => __( 'Sidenav menu item hover color', 'zettaiwp' ),
			'name' => 'menu_item_hover_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#F9F9F9',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5c535380e40d9',
			'label' => __( 'Footer background', 'zettaiwp' ),
			'name' => 'footer_background',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5d13f79ba999c',
			'label' => __( 'See all color', 'zettaiwp' ),
			'name' => 'see_all_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#5f42e7',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5daba73b2d6f5',
			'label' => __( 'Widget titles color', 'zettaiwp' ),
			'name' => 'widget_titles_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#343a40',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5daba7f42d6f6',
			'label' => __( 'Widget titles border', 'zettaiwp' ),
			'name' => 'widget_titles_border',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5da61c24f90b9',
			'label' => __( 'Search result term color', 'zettaiwp' ),
			'name' => 'search_result_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#5f42e7',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5c080067651a4',
			'label' => __( 'Buttons background color', 'zettaiwp' ),
			'name' => 'buttons_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#5f42e7',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5c07fff6651a1',
			'label' => __( 'Buttons text color', 'zettaiwp' ),
			'name' => 'buttons_text_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FFFFFF',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5c080007651a2',
			'label' => __( 'Buttons background hover color', 'zettaiwp' ),
			'name' => 'buttons_hover_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#1a1f34',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5c08004b651a3',
			'label' => __( 'Buttons text hover color', 'zettaiwp' ),
			'name' => 'buttons_text_hover_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FFFFFF',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_6186e0ec47531',
			'label' => __( 'Movie / Series background color', 'zettaiwp' ),
			'name' => 'movie_series_background_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FFFAF0',
			'enable_opacity' => 0,
			'return_format' => 'array',
		),
		array(
			'key' => 'field_618687c73efa3',
			'label' => __( 'Card Color', 'zettaiwp' ),
			'name' => 'card_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FEF5ED',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_61892bc8dca1e',
			'label' => __( 'Movie / Series Card color', 'zettaiwp' ),
			'name' => 'movie_series_card_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FFF',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5d27820752d4a',
			'label' => __( 'Comment Card Color', 'zettaiwp' ),
			'name' => 'comment_card_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#f1f1f1',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5bc4b6d9f80ea',
			'label' => __( 'Home Slider', 'zettaiwp' ),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_5cd6036e740b7',
			'label' => __( 'Activate Slider', 'zettaiwp' ),
			'name' => 'activate_slider',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '15',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5d1fa21d10d38',
			'label' => __( 'Home Slider Title', 'zettaiwp' ),
			'name' => 'home_slider_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5dab81a7fac44',
			'label' => __( 'Home Slider title color', 'zettaiwp' ),
			'name' => 'home_slider_title_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '15',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#212529',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5e4709b4b8e0b',
			'label' => __( 'Home Slider columns', 'zettaiwp' ),
			'name' => 'home_slider_columns',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '15',
				'class' => '',
				'id' => '',
			),
			'default_value' => 3,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'columns',
			'min' => 1,
			'max' => 3,
			'step' => '',
		),
		array(
			'key' => 'field_6187ec3206a53',
			'label' => __( 'Home Slider Height', 'zettaiwp' ),
			'name' => 'home_slider_height',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '15',
				'class' => '',
				'id' => '',
			),
			'default_value' => 420,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5bc5044e7d8a8',
			'label' => __( 'Create slides', 'zettaiwp' ),
			'name' => 'create_slides',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => __( 'Add Slide', 'zettaiwp' ),
			'sub_fields' => array(
				array(
					'key' => 'field_60c4db6e0898e',
					'label' => __( 'Image slider', 'zettaiwp' ),
					'name' => 'image_slider',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'ingmarwp-img-16-9',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'parent_repeater' => 'field_5bc5044e7d8a8',
				),
				array(
					'key' => 'field_60c4dba40898f',
					'label' => __( 'Title slider', 'zettaiwp' ),
					'name' => 'title_slider',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_5bc5044e7d8a8',
				),
				array(
					'key' => 'field_60c4dbb408990',
					'label' => __( 'Link slider', 'zettaiwp' ),
					'name' => 'link_slider',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'parent_repeater' => 'field_5bc5044e7d8a8',
				),
				array(
					'key' => 'field_60c4dbc808991',
					'label' => __( 'Slider button text', 'zettaiwp' ),
					'name' => 'slider_button_text',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_5bc5044e7d8a8',
				),
				array(
					'key' => 'field_60c4dbf208992',
					'label' => __( 'Slide text color', 'zettaiwp' ),
					'name' => 'slide_text_color',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => __( 'White', 'zettaiwp' ),
					'ui_off_text' => __( 'Black', 'zettaiwp' ),
					'parent_repeater' => 'field_5bc5044e7d8a8',
				),
			),
			'rows_per_page' => 20,
		),
		array(
			'key' => 'field_6187f14c22f82',
			'label' => __( 'Home Latest Posts', 'zettaiwp' ),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_618fb930cc972',
			'label' => __( 'Activate', 'zettaiwp' ),
			'name' => 'activate_latest_posts',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5daa580089130',
			'label' => __( 'Latest articles title', 'zettaiwp' ),
			'name' => 'latest_articles_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Latest articles',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5daa5ed2c63ed',
			'label' => __( 'Latest articles title color', 'zettaiwp' ),
			'name' => 'latest_articles_title_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#212529',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5daa5e9cc63ec',
			'label' => __( 'Latest articles view', 'zettaiwp' ),
			'name' => 'latest_articles_view',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => __( 'Normal', 'zettaiwp' ),
			'ui_off_text' => __( 'Modal', 'zettaiwp' ),
		),
		array(
			'key' => 'field_6187e8014b66a',
			'label' => __( 'Latest articles columns', 'zettaiwp' ),
			'name' => 'latest_articles_columns',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5daa5e9cc63ec',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 2,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'Columns',
			'min' => 1,
			'max' => 3,
			'step' => '',
		),
		array(
			'key' => 'field_6187ee16195be',
			'label' => __( 'Latest articles height', 'zettaiwp' ),
			'name' => 'latest_articles_height',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5daa5e9cc63ec',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 420,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5dab1abe0551c',
			'label' => __( 'Latest articles post quantity', 'zettaiwp' ),
			'name' => 'latest_articles_post_qty',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5daa5e9cc63ec',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 4,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'Posts',
			'min' => 1,
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5cc32c08d0ab0',
			'label' => __( 'Home Featured Reviews', 'zettaiwp' ),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_5f4a5bb429232',
			'label' => __( 'Activate', 'zettaiwp' ),
			'name' => 'activate_featured_reviews',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5d05296363d13',
			'label' => __( 'Feat. Reviews title', 'zettaiwp' ),
			'name' => 'featured_reviews_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Featured Reviews',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5dab81dcfac45',
			'label' => __( 'Feat. Reviews title color', 'zettaiwp' ),
			'name' => 'feat_reviews_title_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#212529',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5f4a59ca36dc8',
			'label' => __( 'See all button', 'zettaiwp' ),
			'name' => 'see_all_reviews_button',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5d05290463d12',
			'label' => __( 'Select Featured Reviews', 'zettaiwp' ),
			'name' => 'select_featured_reviews',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'reviews',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 1,
			'return_format' => 'object',
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_5f4a5b0a2922d',
			'label' => __( 'Home Featured Posts', 'zettaiwp' ),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_5f4a5bd629233',
			'label' => __( 'Activate', 'zettaiwp' ),
			'name' => 'activate_featured_posts',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f4a5b132922e',
			'label' => __( 'Feat. Posts title', 'zettaiwp' ),
			'name' => 'featured_posts_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Featured Posts',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f4a5b2a2922f',
			'label' => __( 'Feat. Posts title color', 'zettaiwp' ),
			'name' => 'feat_posts_title_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#212529',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5f4a5b3929231',
			'label' => __( 'Select Featured Posts', 'zettaiwp' ),
			'name' => 'select_featured_posts',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'post',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 1,
			'return_format' => 'object',
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_5d1e22e324806',
			'label' => __( 'Home Featured Categories', 'zettaiwp' ),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6187f3ef6d20e',
			'label' => __( 'Activate', 'zettaiwp' ),
			'name' => 'activate_featured_categories',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5cc318b58cffc',
			'label' => __( 'Feat. Categories Title', 'zettaiwp' ),
			'name' => 'featured_categories_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Featured categories',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5dab81f9fac46',
			'label' => __( 'Feat. Categories title color', 'zettaiwp' ),
			'name' => 'feat_categories_title_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#212529',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_6187f756e40dd',
			'label' => __( 'Feat. Categories height', 'zettaiwp' ),
			'name' => 'feat_categories_height',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => 250,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_618828f9e3736',
			'label' => __( 'Section Columns', 'zettaiwp' ),
			'name' => 'select_cats_columns',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => 2,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'Columns',
			'min' => 1,
			'max' => 4,
			'step' => 1,
		),
		array(
			'key' => 'field_5d83da62b8734',
			'label' => __( 'Select Featured Categories', 'zettaiwp' ),
			'name' => 'select_featured_categories',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'multi_select',
			'allow_null' => 0,
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'object',
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_5cf941014aefb',
			'label' => __( 'Home Movies and Series Slider', 'zettaiwp' ),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_5daa5181fef61',
			'label' => __( 'Activate Movie Slider', 'zettaiwp' ),
			'name' => 'activate_movie_slider',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5d84000133f3b',
			'label' => __( 'Feat. Movies Title', 'zettaiwp' ),
			'name' => 'featured_movies_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'New Movies in Archive',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5dab8216fac47',
			'label' => __( 'Feat. Movies title color', 'zettaiwp' ),
			'name' => 'feat_movies_title_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#212529',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5f4a5a0436dc9',
			'label' => __( 'See all button', 'zettaiwp' ),
			'name' => 'see_all_movies_button',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5d83e6751db7d',
			'label' => __( 'Select Featured Movies', 'zettaiwp' ),
			'name' => 'select_featured_movies',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'movies',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 1,
			'return_format' => 'object',
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_618a702ddd311',
			'label' => __( 'Activate Series Slider', 'zettaiwp' ),
			'name' => 'activate_series_slider',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_618a7042dd312',
			'label' => __( 'Feat. Series Title', 'zettaiwp' ),
			'name' => 'featured_series_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'New Series in Archive',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_618a706cdd313',
			'label' => __( 'Feat. Series title color', 'zettaiwp' ),
			'name' => 'feat_series_title_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#212529',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_618a709edd314',
			'label' => __( 'See all button', 'zettaiwp' ),
			'name' => 'see_all_series_button',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => __( 'Yes', 'zettaiwp' ),
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_618a70bbdd315',
			'label' => __( 'Select Featured Series', 'zettaiwp' ),
			'name' => 'select_featured_series',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'series',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 1,
			'return_format' => 'object',
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_5db21a739c4ed',
			'label' => __( '404 Page', 'zettaiwp' ),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_5db21a969c4ee',
			'label' => __( '404 image', 'zettaiwp' ),
			'name' => '404_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5db21b339c4ef',
			'label' => __( '404 message title', 'zettaiwp' ),
			'name' => '404_message_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Oops! Page not found',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5db21b559c4f0',
			'label' => __( '404 message', 'zettaiwp' ),
			'name' => '404_message',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'We seem to have messed something up. Sorry about that.
Have a look at the address to see if you can spot an error.',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array(
			'key' => 'field_5bc4b6312b1a0',
			'label' => __( 'Social Links', 'zettaiwp' ),
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_5c3e0aa942979',
			'label' => __( 'Facebook', 'zettaiwp' ),
			'name' => 'facebook',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c3e0b3c54c3b',
			'label' => __( 'X', 'zettaiwp' ),
			'name' => 'twitter',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c3e0b8f54c3d',
			'label' => __( 'Instagram', 'zettaiwp' ),
			'name' => 'instagram',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c3e0d8d7526a',
			'label' => __( 'Youtube', 'zettaiwp' ),
			'name' => 'youtube',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c77d4a80362d',
			'label' => __( 'Vimeo', 'zettaiwp' ),
			'name' => 'vimeo',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );